export const mockPosts = [
  {
    id: 1,
    author: "Kai Blackwood",
    handle: "@kai_peaks",
    avatarColor: "#ff9100",
    initials: "KB",
    content: "Summit fever is real. Third attempt on the north face today — finally nailed the crux section. The exposure is absolutely wild up there. #climbing #alpine",
    time: "2m ago",
    likes: 142,
    comments: 23,
    shares: 8,
    tags: ["climbing", "alpine"],
    hasImage: true,
    imageGradient: "from-slate-700 via-slate-600 to-slate-800",
    imageDesc: "North face alpine route"
  },
  {
    id: 2,
    author: "Sierra Dawson",
    handle: "@sierra.runs",
    avatarColor: "#3b82f6",
    initials: "SD",
    content: "6AM trail run in the fog. You can't see the summit but you can feel it. 28km done. Legs are cooked. Soul is full. 🏔️ #trailrunning #ultras",
    time: "15m ago",
    likes: 89,
    comments: 14,
    shares: 3,
    tags: ["trailrunning", "ultras"],
    hasImage: true,
    imageGradient: "from-slate-800 via-slate-700 to-slate-600"
  },
  {
    id: 3,
    author: "Ranger Unit 7",
    handle: "@rangerunit7",
    avatarColor: "#22c55e",
    initials: "R7",
    content: "⚠️ TRAIL ADVISORY: Avalanche risk elevated on the northern approaches. SAR teams on standby. Check your gear, file your plans, travel with a partner. Stay safe out there.",
    time: "32m ago",
    likes: 267,
    comments: 41,
    shares: 89,
    tags: ["safety", "SAR", "advisory"],
    hasImage: false,
    isAlert: true
  },
  {
    id: 4,
    author: "Milo Farren",
    handle: "@milo.explores",
    avatarColor: "#a855f7",
    initials: "MF",
    content: "New gear day 🎒 Just picked up the Hyperlite Mountain Gear Prism pack. 820g for a 40L? The ultralight community is truly built different. Full review incoming.",
    time: "1h ago",
    likes: 203,
    comments: 37,
    shares: 12,
    tags: ["gear", "ultralight", "review"],
    hasImage: true,
    imageGradient: "from-violet-900 via-slate-800 to-slate-700"
  },
  {
    id: 5,
    author: "Zoe Ashford",
    handle: "@zoe_summit",
    avatarColor: "#f43f5e",
    initials: "ZA",
    content: "The thing nobody tells you about high altitude is how it changes your relationship with silence. 4800m, -14°C, just the wind. Completely alone for 3 days. Changed me.",
    time: "2h ago",
    likes: 445,
    comments: 78,
    shares: 34,
    tags: ["highaltitude", "expedition", "mindset"],
    hasImage: true,
    imageGradient: "from-blue-950 via-slate-800 to-slate-900"
  },
  {
    id: 6,
    author: "Finn Rivers",
    handle: "@finn.rivers",
    avatarColor: "#0ea5e9",
    initials: "FR",
    content: "Using TOPO mesh for the first time in a dead zone today. Signal dropped completely at the 18km mark but the crew was still connected. This tech is a game changer for remote operations. 💪 #mesh #offgrid",
    time: "3h ago",
    likes: 312,
    comments: 52,
    shares: 28,
    tags: ["mesh", "offgrid", "TOPO"],
    hasImage: false
  },
  {
    id: 7,
    author: "Ava Chen",
    handle: "@ava.ridge",
    avatarColor: "#f59e0b",
    initials: "AC",
    content: "Ridge running at golden hour hits different. 14km of technical terrain above the clouds. The Southern Alps are unreal this time of year. 📸",
    time: "4h ago",
    likes: 521,
    comments: 63,
    shares: 47,
    tags: ["ridgerunning", "southernalps"],
    hasImage: true,
    imageGradient: "from-orange-950 via-amber-900 to-slate-800"
  },
  {
    id: 8,
    author: "Brennan Wild",
    handle: "@brennan_wild",
    avatarColor: "#10b981",
    initials: "BW",
    content: "PSA: Stop posting your exact GPS coordinates in real-time. Love the sharing culture but please, use delayed posting or general areas. Wildlife, other hikers, and your own safety depend on it.",
    time: "5h ago",
    likes: 892,
    comments: 134,
    shares: 201,
    tags: ["safety", "etiquette"],
    hasImage: false
  },
  {
    id: 9,
    author: "Luna Frost",
    handle: "@luna.frost.runs",
    avatarColor: "#8b5cf6",
    initials: "LF",
    content: "Day 7 of the Spine Route attempt. 412km in. Blisters on blisters, but the mind is sharp. Sleep 3h per night is wild. My crew via TOPO mesh has been lifesaving. 🫀",
    time: "6h ago",
    likes: 1204,
    comments: 289,
    shares: 156,
    tags: ["ultras", "spineroute", "TOPO"],
    hasImage: true,
    imageGradient: "from-purple-950 via-slate-800 to-slate-700"
  },
  {
    id: 10,
    author: "Crew Delta",
    handle: "@crew_delta",
    avatarColor: "#ef4444",
    initials: "CD",
    content: "Training day: Technical rescue scenarios in vertical terrain. Every team member drills anchor builds + patient packaging until it's automatic. Prepare in the gym, execute on the mountain. #SAR #rescue",
    time: "8h ago",
    likes: 445,
    comments: 67,
    shares: 89,
    tags: ["SAR", "rescue", "training"],
    hasImage: true,
    imageGradient: "from-red-950 via-slate-800 to-slate-700"
  },
  {
    id: 11,
    author: "Hana Kita",
    handle: "@hana.kita",
    avatarColor: "#ec4899",
    initials: "HK",
    content: "Sunrise from 3200m. No filter, no edit. Just the mountain and the light. Sometimes the only caption that works is silence. 🌅",
    time: "12h ago",
    likes: 2341,
    comments: 187,
    shares: 445,
    tags: ["sunrise", "mountains", "photography"],
    hasImage: true,
    imageGradient: "from-pink-950 via-orange-900 to-amber-800"
  },
  {
    id: 12,
    author: "Dax Storm",
    handle: "@dax.storm",
    avatarColor: "#6366f1",
    initials: "DS",
    content: "Forecast was wrong again. Surprise whiteout at 2400m. Bivvy gear saved the day. Lesson: always carry a bivy sack, always carry your 10 essentials, always tell someone your plan. Non-negotiable. ⛰️❄️",
    time: "10h ago",
    likes: 934,
    comments: 171,
    shares: 243,
    tags: ["safety", "gear", "survival"],
    hasImage: true,
    imageGradient: "from-indigo-950 via-slate-800 to-slate-700"
  },
  {
    id: 13,
    author: "Skye Linden",
    handle: "@skye.linden",
    avatarColor: "#a78bfa",
    initials: "SL",
    content: "Community shelter project is done! 12 weeks of weekends, 40 volunteers, one completed alpine hut at 2100m. This is what the outdoor community is about. 🏔️❤️ #community #trail #volunteer",
    time: "20h ago",
    likes: 3241,
    comments: 312,
    shares: 567,
    tags: ["community", "volunteer", "trail"],
    hasImage: true,
    imageGradient: "from-violet-950 via-slate-800 to-green-950"
  },
  {
    id: 14,
    author: "Remy Solaris",
    handle: "@remy.solaris",
    avatarColor: "#06b6d4",
    initials: "RS",
    content: "3-day solo loop complete. 67km, 4800m vert. No phone signal for 54 hours. The only 'notification' was a kea stealing my lunch at basecamp. 10/10, would repeat. 🦜",
    time: "16h ago",
    likes: 1567,
    comments: 234,
    shares: 178,
    tags: ["solo", "loop", "newzealand"],
    hasImage: true,
    imageGradient: "from-cyan-950 via-slate-800 to-teal-900"
  },
  {
    id: 15,
    author: "Niko Vance",
    handle: "@niko.vance",
    avatarColor: "#d946ef",
    initials: "NV",
    content: "Just finished a multi-pitch training day on the sea cliffs. 11 pitches, 6 hours, zero falls. The consistency is starting to show. Trust the process. 🧗‍♂️ #climbing #training",
    time: "18h ago",
    likes: 678,
    comments: 91,
    shares: 24,
    tags: ["climbing", "training"],
    hasImage: true,
    imageGradient: "from-fuchsia-950 via-slate-800 to-slate-700"
  },
  {
    id: 16,
    author: "Tana Rios",
    handle: "@tana.rios",
    avatarColor: "#84cc16",
    initials: "TR",
    content: "Wild plant ID walk this morning — found 14 species of edible plants within 500m of the trailhead. Knowledge is the best survival gear. 🌿 Workshop this Sunday if you're in Wanaka!",
    time: "22h ago",
    likes: 423,
    comments: 58,
    shares: 112,
    tags: ["survival", "foraging", "bushcraft"],
    hasImage: false
  },
  {
    id: 17,
    author: "Clem Ashby",
    handle: "@clem.ashby",
    avatarColor: "#f97316",
    initials: "CA",
    content: "Gear test report: Ran the new trail shoes 120km over technical terrain. Verdict: the toe protection is excellent, but the heel stack is too soft for rocky descents. Full writeup on the blog.",
    time: "1d ago",
    likes: 312,
    comments: 47,
    shares: 89,
    tags: ["gear", "review", "trailrunning"],
    hasImage: true,
    imageGradient: "from-orange-950 via-slate-800 to-slate-700"
  },
  {
    id: 18,
    author: "Lex Moreau",
    handle: "@lex.moreau",
    avatarColor: "#38bdf8",
    initials: "LM",
    content: "Night navigation course done ✅. Map, compass, no tech. Reading terrain by headlamp with a 20kg pack is a different beast. Highly recommend — you don't know navigation until the GPS is dead.",
    time: "1d ago",
    likes: 745,
    comments: 102,
    shares: 63,
    tags: ["navigation", "skills", "training"],
    hasImage: true,
    imageGradient: "from-sky-950 via-slate-800 to-indigo-900"
  },
  {
    id: 19,
    author: "Yuki Tanaka",
    handle: "@yuki.tanaka",
    avatarColor: "#e879f9",
    initials: "YT",
    content: "First winter summit! Mount Difficulty, 1592m. Crampons on at 1200m. Everything above that was ice and adrenaline. I cried at the top and I am not even slightly embarrassed. 🏔️❄️ #firstsummit",
    time: "2d ago",
    likes: 3812,
    comments: 421,
    shares: 589,
    tags: ["firstsummit", "winter", "mountains"],
    hasImage: true,
    imageGradient: "from-purple-950 via-blue-950 to-slate-800"
  },
  {
    id: 20,
    author: "Pax Delacroix",
    handle: "@pax.delacroix",
    avatarColor: "#fb923c",
    initials: "PD",
    content: "Reminder that the mountains don't care about your timeline. Turned back 200m from the summit today because conditions were deteriorating fast. The peak will still be there. Safety first, ego never. 🏔️",
    time: "2d ago",
    likes: 5601,
    comments: 634,
    shares: 1120,
    tags: ["safety", "mindset", "alpine"],
    hasImage: false
  },
  {
    id: 21,
    author: "Vera Strand",
    handle: "@vera.strand",
    avatarColor: "#4ade80",
    initials: "VS",
    content: "TOPO crew, who's doing the Kepler Challenge this year? Looking for training partners in the Fiordland area. Drop a 🙋 below! Already have 8 weeks of structured training done. #keplarchallenge #ultramarathon",
    time: "3d ago",
    likes: 287,
    comments: 93,
    shares: 41,
    tags: ["keplarchallenge", "ultramarathon", "community"],
    hasImage: false
  },
  {
    id: 22,
    author: "Orion Beck",
    handle: "@orion.beck",
    avatarColor: "#a3e635",
    initials: "OB",
    content: "Wilderness first aid refresher complete. Reviewed hypothermia management, altitude sickness, fracture immobilisation, and wound closure. Everyone in the backcountry should have at least WFA cert. Non-negotiable. 🩹",
    time: "3d ago",
    likes: 1089,
    comments: 145,
    shares: 298,
    tags: ["firstaid", "safety", "backcountry"],
    hasImage: false,
    isAlert: false
  },
];

export const mockGearItems = [
  { id: 1, name: "Petzl Sirocco Helmet", category: "Safety", weight: "170g", status: "OK", lastCheck: "2d ago", notes: "Minor scuff on left side, structurally sound" },
  { id: 2, name: "Black Diamond Momentum Harness", category: "Safety", weight: "380g", status: "CHECK", lastCheck: "14d ago", notes: "Belay loop showing minor wear — inspect before next use" },
  { id: 3, name: "Petzl GriGri+ Belay Device", category: "Safety", weight: "175g", status: "OK", lastCheck: "5d ago", notes: "Cam mechanism clean, anti-panic function tested" },
  { id: 4, name: "Hyperlite Mountain Gear Prism 40L", category: "Pack", weight: "820g", status: "OK", lastCheck: "1d ago", notes: "Hip belt stitching intact, all buckles working" },
  { id: 5, name: "MSR Hubba Hubba NX2 Tent", category: "Shelter", weight: "1530g", status: "OK", lastCheck: "7d ago", notes: "Seams re-sealed. Poles inspected." },
  { id: 6, name: "Western Mountaineering UltraLite Sleeping Bag", category: "Sleep", weight: "510g", status: "OK", lastCheck: "3d ago", notes: "850fp down, freshly washed and lofted" },
  { id: 7, name: "Jetboil Flash Stove", category: "Cook", weight: "371g", status: "LOW FUEL", lastCheck: "1d ago", notes: "Approximately 1/4 canister remaining — restock before trip" },
  { id: 8, name: "Garmin inReach Mini 2", category: "Navigation", weight: "100g", status: "OK", lastCheck: "1d ago", notes: "Subscription active, battery at 100%, firmware updated" },
  { id: 9, name: "Black Diamond Spot 400-R Headlamp", category: "Light", weight: "95g", status: "OK", lastCheck: "4d ago", notes: "Battery full, all modes tested" },
  { id: 10, name: "Lifestraw Peak Series Water Filter", category: "Hydration", weight: "64g", status: "OK", lastCheck: "10d ago", notes: "Membrane clear, flow rate normal" },
  { id: 11, name: "BCA Float 32 Avalanche Airbag", category: "Safety", weight: "2890g", status: "CHECK", lastCheck: "30d ago", notes: "Annual service overdue — schedule before ski season" },
  { id: 12, name: "Mammut Bivy Sack", category: "Emergency", weight: "310g", status: "OK", lastCheck: "6d ago", notes: "Seal intact, packed correctly" }
];

export const mockWeather = [
  {
    id: 1,
    location: "Mt Aspiring / Tititea",
    elevation: "2340m",
    condition: "Partly Cloudy",
    temp: -4,
    feelsLike: -11,
    wind: { speed: 45, direction: "WSW", gusts: 72 },
    humidity: 78,
    forecast: [
      { day: "Today", high: -2, low: -9, condition: "Partly Cloudy" },
      { day: "Tue", high: 1, low: -7, condition: "Clear" },
      { day: "Wed", high: -1, low: -12, condition: "Snow" },
      { day: "Thu", high: -5, low: -14, condition: "Heavy Snow" },
      { day: "Fri", high: 0, low: -8, condition: "Clearing" }
    ],
    alerts: ["Strong wind warning above 1800m"],
    aiSummary: "Stable window for summit approach Tuesday only. Significant deterioration Wed–Thu. High avalanche risk on NW aspects from Thursday."
  },
  {
    id: 2,
    location: "Routeburn Track",
    elevation: "1255m",
    condition: "Overcast",
    temp: 8,
    feelsLike: 4,
    wind: { speed: 22, direction: "SW", gusts: 38 },
    humidity: 92,
    forecast: [
      { day: "Today", high: 9, low: 4, condition: "Overcast" },
      { day: "Tue", high: 7, low: 2, condition: "Rain" },
      { day: "Wed", high: 5, low: 1, condition: "Heavy Rain" },
      { day: "Thu", high: 8, low: 3, condition: "Showers" },
      { day: "Fri", high: 12, low: 5, condition: "Clearing" }
    ],
    alerts: ["Heavy rain warning — 150mm expected 48h"],
    aiSummary: "Significant multi-day rain event incoming. River levels will rise sharply by Tuesday night. Cross-country travel hazardous Wed–Thu."
  },
  {
    id: 3,
    location: "Ben Lomond, Queenstown",
    elevation: "1748m",
    condition: "Clear",
    temp: 3,
    feelsLike: -2,
    wind: { speed: 18, direction: "N", gusts: 24 },
    humidity: 55,
    forecast: [
      { day: "Today", high: 5, low: -1, condition: "Clear" },
      { day: "Tue", high: 7, low: 1, condition: "Clear" },
      { day: "Wed", high: 6, low: 0, condition: "Partly Cloudy" },
      { day: "Thu", high: 4, low: -2, condition: "Partly Cloudy" },
      { day: "Fri", high: 9, low: 3, condition: "Clear" }
    ],
    alerts: [],
    aiSummary: "Excellent stable window this week. High pressure holding. Perfect conditions for summit, visibility 50km+."
  },
  {
    id: 4,
    location: "Tongariro Alpine Crossing",
    elevation: "1967m",
    condition: "Volcanic Haze",
    temp: 6,
    feelsLike: 1,
    wind: { speed: 35, direction: "SE", gusts: 55 },
    humidity: 68,
    forecast: [
      { day: "Today", high: 8, low: 2, condition: "Hazy" },
      { day: "Tue", high: 10, low: 3, condition: "Partly Cloudy" },
      { day: "Wed", high: 12, low: 5, condition: "Clear" },
      { day: "Thu", high: 11, low: 4, condition: "Clear" },
      { day: "Fri", high: 7, low: 1, condition: "Rain" }
    ],
    alerts: ["Volcanic activity advisory — check GNS before departure"],
    aiSummary: "SE winds expected to ease Tuesday. Clear summit window Wed–Thu is ideal for the crossing. A front arrives Friday — complete your traverse by Thursday evening."
  },
  {
    id: 5,
    location: "Mueller Hut, Aoraki/Mt Cook",
    elevation: "1800m",
    condition: "Snow Showers",
    temp: -7,
    feelsLike: -15,
    wind: { speed: 62, direction: "SW", gusts: 95 },
    humidity: 88,
    forecast: [
      { day: "Today", high: -5, low: -16, condition: "Heavy Snow" },
      { day: "Tue", high: -8, low: -18, condition: "Blizzard" },
      { day: "Wed", high: -4, low: -12, condition: "Snow Showers" },
      { day: "Thu", high: 0, low: -9, condition: "Clearing" },
      { day: "Fri", high: 3, low: -5, condition: "Mostly Clear" }
    ],
    alerts: [
      "Blizzard warning — visibility near zero Tuesday",
      "Extreme windchill advisory — hypothermia risk critical"
    ],
    aiSummary: "Do not attempt approach Monday or Tuesday. Severe blizzard with near-zero visibility and extreme windchill. Conditions stabilise Thursday. First viable summit window opens Friday morning — brief but significant."
  }
];

export const mockCrewMembers = [
  { id: 1, name: "Kai Blackwood", handle: "@kai_peaks", distance: "0.3km", status: "Active", avatarColor: "#ff9100", initials: "KB", lastSeen: "Just now", activity: "Climbing" },
  { id: 2, name: "Sierra Dawson", handle: "@sierra.runs", distance: "1.2km", status: "Moving", avatarColor: "#3b82f6", initials: "SD", lastSeen: "2m ago", activity: "Trail Running" },
  { id: 3, name: "Ava Chen", handle: "@ava.ridge", distance: "2.8km", status: "Stationary", avatarColor: "#f59e0b", initials: "AC", lastSeen: "15m ago", activity: "Ridge Walk" },
  { id: 4, name: "Finn Rivers", handle: "@finn.rivers", distance: "4.1km", status: "Active", avatarColor: "#0ea5e9", initials: "FR", lastSeen: "5m ago", activity: "Hiking" },
  { id: 5, name: "Luna Frost", handle: "@luna.frost.runs", distance: "7.3km", status: "Moving", avatarColor: "#8b5cf6", initials: "LF", lastSeen: "1m ago", activity: "Ultra Running" },
];
